name: AephoutMCEssentials
main: me.AephoutMC.Essentials.Main
author: The_FrosTy_Clan
version: 1a
commands:
  gmc:
    description: Syntax, /gmc <player>
    permission: AephoutMCEssentials.commands.gmc
    permission-message: You don't have access to this command.
  gms:
    description: Syntax, /gms <player>
    permission: AephoutMCEssentials.commands.gms
    permission-message: You don't have access to this command.
  gma:
    description: Syntax, /gma <player>
    permission: AephoutMCEssentials.commands.gma
    permission-message: You don't have access to this command.
  gmspec:
    description: Syntax, /gmspec <player>
    permission: AephoutMCEssentials.commands.gmspec
    permission-message: You don't have access to this command.
  op:
    description: Syntax, /op <player>
    permission: AephoutMCEssentials.commands.op
    permission-message: You don't have access to this command.
  deop:
    description: Syntax, /deop <player>
    permission: AephoutMCEssentials.commands.deop
    permission-message: You don't have access to this command.
  fly:
    description: Syntax, /fly <player>
    permission: AephoutMCEssentials.commands.fly
    permission-message: You don't have access to this command.
  heal:
    description: Heal yourself or Others.
    permission: AephoutMCEssentials.commands.heal
    permission-message: You don't have access to this command.
  feed:
    description: Syntax, /feed <player>
    permission: AephoutMCEssentials.commands.feed
    permission-message: You don't have access to this command.
  ci:
    description: Syntax, /ci <player>
    permission: AephoutMCEssentials.commands.ci
    permission-message: You don't have access to this command.
    aliases: [clearinv, clearinventory]
  workbench:
    description: Syntax, /workbench
    permission: AephoutMCEssentials.commands.workbench
    permission-message: You don't have access to this command.
    aliases: [bench, crafting]
  echest:
    description: Syntax, /echest
    permission: AephoutMCEssentials.commands.echest
    permission-message: You don't have access to this command.
    aliases: [enderchest, myechest]
  list:
    description: Display all Online Players.
    permission: AephoutMCEssentials.commands.list
    permission-message: You don't have access to this command.
  sip:
    description: Check a Players IP.
    permission: AephoutMCEssentials.commands.seen
    permission-message: You don't have access to this command.